version = 3.9.10
runner.dialect = scala3
maxColumn = 120
lineEndings = windows
danglingParentheses.defnSite = false
danglingParentheses.callSite = false
#danglingParentheses.bracketDefnSite = false
#danglingParentheses.bracketCallSite = false
align.openParenDefnSite = true
align.openParenCallSite = true
align.tokens = some
assumeStandardLibraryStripMargin = true
align.stripMargin = true
indent.callSite = 2
newlines.source = keep
newlines.forceBeforeMultilineAssign = never
newlines.implicitParamListModifierPrefer = before
spaces.inImportCurlyBraces = false
spaces.withinContextBoundBraces = never
